let state=null, selectedRunId=null, selectedBeamId=null;
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(n){return Number(n||0).toLocaleString();}
function pill(x,cls=''){return `<span class="pill ${esc(cls)}">${esc(x)}</span>`;}
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok||d?.error)throw new Error(d?.error||t||r.statusText);return d;}
async function loadState(){state=await api('/api/state');if(!selectedRunId&&state.sessions.length)selectedRunId=state.sessions[0].run_id;if(!selectedBeamId&&state.beams?.length)selectedBeamId=state.beams[0].beam_id;render();if(selectedRunId)loadSession(selectedRunId,false).catch(()=>{});if(selectedBeamId)loadBeam(selectedBeamId,false).catch(()=>{});}
function render(){if(!state)return;$('rootLabel').textContent=state.root;$('generatedAt').textContent=`generated ${state.generated_at}`;renderStats();renderBeams();renderOutcomes();renderExperiments();renderMemoryFSM();renderSessions();renderClaims();renderDirections();$('humanContext').textContent=state.human_context||'';}
function renderStats(){const s=state.stats||{},st=s.status_counts||{},u=s.usage_totals||{};const cards=[['Beams',s.beam_count||0],['Beam nodes',s.beam_node_count||0],['Sessions',s.session_count],['Passed',st.PASSED||0],['Unreviewed claims',s.unreviewed_conclusion_count],['Approx prompt tokens',u.approx_prompt_tokens||0],['Outcomes',s.outcome_count||0],['Experiments',s.experiment_count||0],['Memory FSM',s.memory_fsm_count||0],['Est. $',s.provider_estimated_usd||0]];$('stats').innerHTML=cards.map(([label,num])=>`<div class="stat"><div class="num">${fmt(num)}</div><div class="label">${esc(label)}</div></div>`).join('');}
function renderBeams(){const filter=$('beamFilter')?.value||'all';const beams=(state.beams||[]).filter(b=>filter==='all'||b.status===filter);$('beamTable').innerHTML=`<thead><tr><th>Status</th><th>Beam</th><th>Goal</th><th>Budget/usage</th><th>Best</th><th>Dir</th></tr></thead><tbody>${beams.map(b=>`<tr data-beam="${esc(b.beam_id)}"><td class="${esc(b.status)}">${esc(b.status)}</td><td><code>${esc(b.beam_id)}</code></td><td>${esc(b.goal_id)}<br/><span class="muted small">${esc(b.objective||'')}</span></td><td>${fmt(b.session_count)} sessions / ${fmt(b.node_count)} nodes</td><td>${esc((b.best_node_ids||[]).join(', ')||'-')}</td><td><code>${esc(b.beam_dir||'')}</code></td></tr>`).join('')}</tbody>`;$('beamTable').querySelectorAll('tr[data-beam]').forEach(tr=>tr.addEventListener('click',()=>loadBeam(tr.dataset.beam)));}
async function loadBeam(beamId,rerender=true){selectedBeamId=beamId;const d=await api(`/api/beam?beam_id=${encodeURIComponent(beamId)}`);const nodes=d.nodes||[], edges=d.edges||[];const byParent={};for(const n of nodes){const p=n.parent_node_id||'none';(byParent[p] ||= []).push(n);}for(const k of Object.keys(byParent)){byParent[k].sort((a,b)=>(b.score?.score||0)-(a.score?.score||0));}
function row(n,depth=0){const score=n.score?.score??n.score??'';const cls=n.status||'';let html=`<div class="beam-node" style="margin-left:${depth*18}px"><span class="${esc(cls)}">${esc(n.status)}</span> ${pill('d'+(n.depth??0))} <code>${esc(n.node_id)}</code> score=<b>${esc(score)}</b> human=${esc(n.human_verdict||'unreviewed')}<br/><span>${esc(n.title||n.objective||'')}</span>${n.run_id?`<br/><button onclick="loadSession('${esc(n.run_id)}')">open session</button> <button onclick="markBeamNode('${esc(n.node_id)}','accepted')">accept node</button> <button onclick="markBeamNode('${esc(n.node_id)}','wrong')">wrong node</button>`:''}</div>`;for(const c of (byParent[n.node_id]||[]))html+=row(c,depth+1);return html;}
const roots=(byParent.none||[]).concat(byParent[null]||[]);let tree='';for(const r of nodes.filter(n=>n.node_id==='root'))tree+=row(r,0);if(!tree)tree=nodes.map(n=>row(n,0)).join('');$('beamTree').innerHTML=tree||'<p class="muted">No nodes.</p>';
const best=d.summary?.best_nodes?.[0]||nodes.filter(n=>n.node_id!=='root').sort((a,b)=>(b.score?.score||0)-(a.score?.score||0))[0];const lines=[];lines.push(`# Beam ${beamId}`);lines.push(`status: ${d.summary?.status||d.beam?.status||'UNKNOWN'}`);lines.push(`reason: ${d.summary?.reason||''}`);lines.push(`nodes: ${nodes.length} edges: ${edges.length}`);if(best){lines.push(`\n## Best node`);lines.push(`node: ${best.node_id}`);lines.push(`run: ${best.run_id}`);lines.push(`status: ${best.status}`);lines.push(`score: ${JSON.stringify(best.score)}`);lines.push(`objective: ${best.objective}`);lines.push(`distill: ${best.distill_summary||''}`);}lines.push(`\n## Recent events`);for(const e of (d.events||[]).slice(-50))lines.push(`${e.ts} ${e.event} ${e.node_id||''} [${e.status||'-'}]`);$('beamDetail').textContent=lines.join('\n');if(rerender)renderBeams();}
async function markBeamNode(nodeId,verdict){const note=prompt(`Human note for beam node ${verdict}:`,'')||'';await api('/api/feedback',{method:'POST',body:JSON.stringify({target_type:'beam_node',target_id:nodeId,verdict,note})});await loadState();}

function renderOutcomes(){const rows=state.outcomes||[];const el=$('outcomeTable');if(!el)return;el.innerHTML=`<thead><tr><th>Status</th><th>Run</th><th>Rubric</th><th>Score</th><th>Feedback</th></tr></thead><tbody>${rows.map(o=>`<tr data-run="${esc(o.run_id)}"><td class="${esc(o.status)}">${esc(o.status)}</td><td><code>${esc(o.run_id||'')}</code></td><td>${esc(o.rubric_id||'-')}</td><td><b>${esc(o.score)}</b> / ${esc(o.pass_threshold)}</td><td>${esc((o.feedback||'').split('\n').slice(0,3).join(' | '))}</td></tr>`).join('')}</tbody>`;el.querySelectorAll('tr[data-run]').forEach(tr=>tr.addEventListener('click',()=>loadSession(tr.dataset.run)));}
function renderExperiments(){const rows=state.experiments||[], sum=state.experiment_summary||{};const summary=$('experimentSummary');if(summary)summary.innerHTML=`${pill('count '+(sum.count||0))}${pill('structural ratio '+((sum.structural_ratio||0).toFixed?sum.structural_ratio.toFixed(2):sum.structural_ratio))}${pill('kept '+((sum.by_status||{}).kept||0))}${pill('discarded '+((sum.by_status||{}).discarded||0))}`;const el=$('experimentTable');if(!el)return;el.innerHTML=`<thead><tr><th>Status</th><th>Experiment</th><th>Type</th><th>Score</th><th>Hypothesis</th><th>Run</th></tr></thead><tbody>${rows.map(e=>{const m=e.metrics||{},score=m.score??m.rubric_score??'-';return `<tr data-run="${esc(e.run_id||'')}"><td class="${esc(e.status)}">${esc(e.status)}</td><td><code>${esc(e.experiment_id)}</code></td><td>${esc(e.type||'-')}</td><td>${esc(score)}</td><td>${esc(e.hypothesis||'')}</td><td><code>${esc(e.run_id||'')}</code></td></tr>`}).join('')}</tbody>`;el.querySelectorAll('tr[data-run]').forEach(tr=>{if(tr.dataset.run)tr.addEventListener('click',()=>loadSession(tr.dataset.run));});}
function renderMemoryFSM(){const cov=state.memory_coverage||{}, rows=state.memory_fsm||[];const c=$('memoryCoverage');if(c)c.innerHTML=`${pill('total '+(cov.total||0))}${pill('verified coverage '+(((cov.verified_memory_coverage||0).toFixed)?cov.verified_memory_coverage.toFixed(2):cov.verified_memory_coverage))}${pill('consult rate '+(((cov.consult_rate||0).toFixed)?cov.consult_rate.toFixed(2):cov.consult_rate))}${pill('open failures '+(cov.open_failure_notes||0))}`;const el=$('memoryTable');if(!el)return;el.innerHTML=`<thead><tr><th>State</th><th>Memory</th><th>Claim</th><th>Rule</th></tr></thead><tbody>${rows.map(m=>`<tr><td class="${esc(m.state)}">${esc(m.state)}</td><td><code>${esc(m.memory_id)}</code><br/><span class="muted small">${esc(m.domain||'')}</span></td><td>${esc(m.claim||'')}</td><td>${esc(m.general_rule||'-')}</td></tr>`).join('')}</tbody>`;}
function renderSessions(){const filter=$('sessionFilter').value;const sessions=(state.sessions||[]).filter(s=>filter==='all'||s.status===filter);$('sessionTable').innerHTML=`<thead><tr><th>Status</th><th>Goal</th><th>Beam</th><th>Task type</th><th>Reason</th><th>Human</th><th>Usage</th><th>Run</th></tr></thead><tbody>${sessions.map(s=>{const u=s.usage||{};return `<tr data-run="${esc(s.run_id)}"><td class="${esc(s.status)}">${esc(s.status)}</td><td>${esc(s.goal_id)}</td><td>${s.beam_id?`<code>${esc(s.beam_id)}</code><br/><span class="muted small">${esc(s.beam_node_id||'')}</span>`:'-'}</td><td>${esc(s.task_type||'-')}</td><td>${esc(s.reason||'')}</td><td class="${esc(s.human_verdict||'unreviewed')}">${esc(s.human_verdict||'unreviewed')}</td><td>${fmt(u.agent_calls)} calls / ${fmt(u.approx_prompt_tokens)} tok</td><td><code>${esc(s.run_id)}</code></td></tr>`}).join('')}</tbody>`;$('sessionTable').querySelectorAll('tr[data-run]').forEach(tr=>tr.addEventListener('click',()=>loadSession(tr.dataset.run)));}
async function loadSession(runId,rerender=true){selectedRunId=runId;const d=await api(`/api/session?run_id=${encodeURIComponent(runId)}`);$('detailSubtitle').innerHTML=`<code>${esc(runId)}</code>`;$('sessionVerdictButtons').innerHTML=`<button class="good" onclick="markSession('accepted')">Accept</button> <button class="bad" onclick="markSession('wrong')">Wrong</button> <button class="warn" onclick="markSession('needs_followup')">Needs follow-up</button>`;const lines=[];lines.push(`# ${runId}`);lines.push(`status: ${d.final?.status||d.session?.status||'UNKNOWN'}`);lines.push(`reason: ${d.final?.reason||d.session?.reason||''}`);lines.push(`run_dir: ${d.run_dir}`);if(d.final?.beam_node)lines.push(`beam: ${d.final.beam_node.beam_id} node=${d.final.beam_node.node_id} parent=${d.final.beam_node.parent_node_id}`);if(d.human_feedback)lines.push(`human: ${d.human_feedback.verdict} - ${d.human_feedback.note||''}`);lines.push('\n## Compact summary\n');lines.push(d.compact||'(none)');lines.push('\n## Report\n');lines.push(d.report||'(none)');lines.push('\n## Events\n');for(const e of (d.events||[]).slice(-100))lines.push(`${e.ts} ${e.event} [${e.status||'-'}] round=${e.round??'-'}`);$('sessionDetail').textContent=lines.join('\n');if(rerender)renderSessions();}
function renderClaims(){const filter=$('claimFilter').value;let claims=state.conclusions||[];if(filter!=='all')claims=claims.filter(c=>(c.human_status||c.human_verdict||'unreviewed')===filter);$('claimList').innerHTML=claims.slice(0,300).map(c=>`<div class="claim ${esc(c.human_status||c.human_verdict||'unreviewed')}"><div class="row">${pill(c.item_type||c.kind)}${pill(c.goal_id||'-')}${c.beam_id?pill('beam '+c.beam_id):''}${pill(c.human_status||c.human_verdict||'unreviewed',c.human_status||c.human_verdict||'unreviewed')}</div><div class="text">${esc(c.claim)}</div>${c.human_note?`<p class="muted">Human note: ${esc(c.human_note)}</p>`:''}<textarea id="note-${esc(c.claim_id)}" placeholder="Human note for this conclusion…"></textarea><div class="row" style="margin-top:8px"><button class="good" onclick="markClaim('${esc(c.claim_id)}','correct')">Correct</button><button class="bad" onclick="markClaim('${esc(c.claim_id)}','wrong')">Wrong</button><button class="warn" onclick="markClaim('${esc(c.claim_id)}','uncertain')">Uncertain</button><button onclick="markClaim('${esc(c.claim_id)}','stale')">Stale</button></div><p class="muted small"><code>${esc(c.claim_id)}</code> · ${esc(c.source_distill_path||'')}</p></div>`).join('')||'<p class="muted">No conclusions match.</p>';}
async function markClaim(id,verdict){const c=(state.conclusions||[]).find(x=>x.claim_id===id);const note=$(`note-${id}`)?.value||'';await api('/api/feedback',{method:'POST',body:JSON.stringify({target_type:'claim',target_id:id,verdict,note,run_id:c?.run_id,goal_id:c?.goal_id,claim:c?.claim})});await loadState();}
async function markSession(verdict){if(!selectedRunId)return;const note=prompt(`Human note for session ${verdict}:`,'')||'';await api('/api/feedback',{method:'POST',body:JSON.stringify({target_type:'session',target_id:selectedRunId,verdict,note,metadata:{run_id:selectedRunId}})});await loadState();}
function renderDirections(){$('directionList').innerHTML=(state.directions||[]).map(d=>`<div class="claim"><div class="row">${pill(d.priority||'P2')}${pill(d.scope||'project')}${pill(d.status||'active')}</div><div class="text">${esc(d.text)}</div><p class="muted small">${esc(d.created_at)} · <code>${esc(d.guidance_id)}</code></p></div>`).join('')||'<p class="muted">No directions yet.</p>';}
$('refreshBtn').addEventListener('click',loadState);$('sessionFilter').addEventListener('change',renderSessions);$('claimFilter').addEventListener('change',renderClaims);$('beamFilter').addEventListener('change',renderBeams);$('directionForm').addEventListener('submit',async e=>{e.preventDefault();const text=$('directionText').value.trim();if(!text)return;await api('/api/direction',{method:'POST',body:JSON.stringify({text,priority:$('directionPriority').value,scope:$('directionScope').value,create_task:$('directionTask').checked})});$('directionText').value='';await loadState();});
loadState().catch(err=>{document.body.innerHTML=`<pre style="padding:24px;color:#ff6961">${esc(err.stack||err.message||err)}</pre>`});
