"""Canonical verifier-gated autonomy runtime for Sisyfus."""

from .adapters import CommandPlanner, JsonInboxSensor, RunbookPlanner, decision_from_mapping
from .discovery import DiscoveryPolicy, OpportunityDiscovery, Sensor, SensorError, SensorScanResult
from .models import (
    AssuranceLevel,
    CapabilityResult,
    ContinuationState,
    Decision,
    DecisionAction,
    DecisionKind,
    ExperienceLesson,
    ExperiencePolarity,
    OpportunityProposal,
    OpportunitySignal,
    OpportunityStatus,
    RiskTier,
    TickResult,
    Verdict,
    VerificationMode,
    VerificationResult,
)
from .policy import (
    AttemptBudgetExceeded,
    AutonomyError,
    AutonomyPolicy,
    Capability,
    CapabilityRegistry,
    ConcurrentUpdate,
    IdempotencyConflictError,
    IncompatibleSchemaError,
    InvalidTransition,
    LeaseLost,
    NotFoundError,
    Planner,
    PolicyDeniedError,
    UnknownCommitError,
    VerificationRequiredError,
    Verifier,
)
from .runtime import AutonomousRuntime, LeaseHeartbeat, register_safe_builtins
from .store import AutonomyStore
from .supervisor import AutonomousSupervisor, Supervisor, SupervisorConfig, SupervisorStats

__all__ = [
    "AssuranceLevel",
    "AttemptBudgetExceeded",
    "AutonomyError",
    "AutonomyPolicy",
    "AutonomyStore",
    "AutonomousRuntime",
    "AutonomousSupervisor",
    "Capability",
    "CapabilityRegistry",
    "CapabilityResult",
    "CommandPlanner",
    "ConcurrentUpdate",
    "ContinuationState",
    "Decision",
    "DecisionAction",
    "DecisionKind",
    "DiscoveryPolicy",
    "ExperienceLesson",
    "ExperiencePolarity",
    "IdempotencyConflictError",
    "IncompatibleSchemaError",
    "InvalidTransition",
    "JsonInboxSensor",
    "LeaseHeartbeat",
    "LeaseLost",
    "NotFoundError",
    "OpportunityDiscovery",
    "OpportunityProposal",
    "OpportunitySignal",
    "OpportunityStatus",
    "Planner",
    "PolicyDeniedError",
    "RiskTier",
    "RunbookPlanner",
    "Sensor",
    "SensorError",
    "SensorScanResult",
    "Supervisor",
    "SupervisorConfig",
    "SupervisorStats",
    "TickResult",
    "UnknownCommitError",
    "Verdict",
    "VerificationMode",
    "VerificationRequiredError",
    "VerificationResult",
    "Verifier",
    "decision_from_mapping",
    "register_safe_builtins",
]
